# =================================================================================================
#     Setup
# =================================================================================================

# Packages
import pandas as pd
import os

# Point to config file
configfile: "config/config.yaml"

# Read in sample names
with open(config["samples"]) as f:
    SAMPLES = [line.strip() for line in f]

# State reads
READS = ['1', '2']

# =================================================================================================
#     Default "All" Target Rule
# =================================================================================================

# This rule requests that other rules be run.

rule all:
    input:
        expand("results/sorted/{sample}.bam.bai", sample=SAMPLES),              # indexed bams
        expand("results/dedup/{sample}.bam", sample=SAMPLES),                   # deduplicated bams
        expand("results/dedup/{sample}.stats", sample=SAMPLES),                 # mapping stats
        expand("results/dedup/{sample}.depth", sample=SAMPLES),                 # depth stats
        "results/mapping_summary.txt"                                           # summary of stats
        "results/avg_depth.txt"                                                 # average depth
        expand("results/mapdamage/{sample}/Runtime_log.txt", sample=SAMPLES)    # mapdamage results

localrules:
    all

# =================================================================================================
#     Rule Modules
# =================================================================================================

include: "rules/map.smk"
include: "rules/damage.smk"