clean_reads_dir: "/data/biol-silvereye/ball6625/nf-polish/museum-results/05.low_complex"
samples: "/data/biol-silvereye/ball6625/map-pipeline/samples.txt"
reference_genome: "/data/biol-silvereye/ball6625/ref-genome/Zlat_2_Tgutt_ZW.fasta"